require("util.globals")
require("util.globals-data")

-- Files that create things needed in subsequent files.
require("data.broad-changes.fluid-boxes")

-- Files that create new protos.
require("data.pre-space.gases")
require("data.broad-changes.map-gen-preset")
require("data.broad-changes.remove-mapgen-presets")
require("data.pre-space.gunpowder")
require("data.pre-space.rubber")
require("data.pre-space.sand-and-glass")
require("data.pre-space.ash")
require("data.misc")
require("data.pre-space.char")
require("data.broad-changes.crafting-categories")
require("data.broad-changes.gui")
require("data.broad-changes.character-stats")
require("data.broad-changes.diurnal-dynamics")
require("data.tech-progression.labs")
require("data.metallurgy.metallurgy-d")
require("data.metallurgy.machine-parts")
require("data.metallurgy.rust")
require("data.petrochem.main")
require("data.cryo.main")
require("data.boilers-furnaces.main")
require("data.electrolysis.electrolysis-plant")
require("data.electrolysis.electrodes")
require("data.pre-space.cement")
require("data.pre-space.stone-processing")
require("data.acids-bases.main")
require("data.frozen.main")
require("data.circuits-modules.recipes-etc")
require("data.circuits-modules.primed-circuits")
require("data.circuits-modules.priming-buildings")
require("data.filtration.filtration-plant")
require("data.filtration.filters")
require("data.pre-space.freshwater")
require("data.pre-space.ammonia")
require("data.broad-changes.briefing")
require("data.early-agriculture.tree-farming")
require("data.early-agriculture.wood")
require("data.pre-space.storage-tanks")
require("data.pre-space.handcrank")
require("data.pre-space.cargo-ships")
require("data.space.rocket-parts-outside-silos")
require("data.pre-space.deep-drill")
require("data.pre-space.air-separator")
require("data.pre-space.exothermic-plant")
require("data.tech-progression.mech-armor")
require("data.broad-changes.planet-drop-techs")
require("data.pre-space.shotgun-turrets")
require("data.circuits-modules.beacons")
require("data.pre-space.personal-battery-generator")
require("data.pre-space.early-equipment-grids")
require("data.pre-space.landmines")
require("data.pre-space.water-etc")
require("data.pre-space.condensing-turbine")
require("data.pre-space.drill-nodes")
require("data.broad-changes.invisible-fluid-connectors")
require("data.circuits-modules.regulators")
require("data.circuits-modules.silicon")
require("data.circuits-modules.clean-assemblers")
require("data.pre-space.mini-assembler")
require("data.crushing.main")
require("data.heat-shuttles.nuclear-reactors")
require("data.heat-shuttles.remove-heat-pipes")

-- Editing planets
require("data.pre-space.misc")
require("data.pre-space.nauvis-worldgen")
require("data.vulcanus.main")
require("data.fulgora.main")
require("data.gleba.main")
require("data.nauvis-part-two.main")
require("data.aquilo.main")

-- Files that create protos, and require previous protos.
require("data.space.main")
require("data.pre-space.gas-vent")
require("data.pre-space.waste-pump")
require("data.pre-space.vent-recipes")
require("data.broad-changes.barrelling")
require("data.intermediate-factors.main")
require("data.broad-changes.fuel")
require("data.heat-shuttles.fuels")
require("data.tech-progression.tech-rate-triggers")
require("data.vulcanus.no-lava-in-pipes")

-- Files that adjust protos
require("data.circuits-modules.remove-modules")
require("data.broad-changes.surface-properties")
require("data.tech-progression.advanced-logistics")
require("data.infra.main")
require("data.broad-changes.ocean-dumping")
require("data.tech-progression.main")
require("data.broad-changes.stack-sizes")
require("data.broad-changes.quality")