require("util.globals")
require("util.globals-data")

-- Files that create things needed in subsequent files.
require("data.crafting-categories")
require("data.fluid-boxes")

-- Files that create new protos.
require("data.char-furnace") -- TODO need to adjust this so quality also affects power consumption.
require("data.early-equipment-grids")
require("data.map-gen-preset")
require("data.remove-mapgen-presets")
require("data.gunpowder")
require("data.rubber")
require("data.sand-and-glass")
require("data.ash")
require("data.misc")
require("data.labs")
require("data.metallurgy.metallurgy-d")
require("data.metallurgy.machine-parts")
require("data.metallurgy.rust")
require("data.petrochem.main")
require("data.cement")
require("data.circuits-modules.circuit-recipes-intermediates")
require("data.filtration")
require("data.ammonia")
require("data.niter")
require("data.briefing")
require("data.tree-farming")
require("data.storage-tanks")
require("data.handcrank")
require("data.heating-towers")
require("data.cargo-ships")
require("data.rocket-parts-outside-silos")
require("data.deep-drill")
require("data.mech-armor")
require("data.planet-drop-techs")
require("data.shotgun-turrets")
require("data.beacons")

-- Planets
require("data.nauvis-part-one.misc")
require("data.nauvis-part-one.worldgen")
require("data.vulcanus.main")
require("data.fulgora.main") -- TODO need to adjust battery-chargers so quality affects power consumption.
require("data.gleba.main")
require("data.nauvis-part-two.main")
require("data.aquilo.main")

-- Files that create protos, and require previous protos.
require("data.gas-vent")
require("data.waste-pump")
require("data.barrelling")
require("data.intermediate-factors.main")
require("data.fuel")
require("data.space.main")
require("data.tech-rate-triggers")

-- Files that adjust protos
require("data.item-groups")
require("data.surface-properties")
require("data.advanced-logistics")
require("data.infra.main")
require("data.ocean-dumping")
require("data.tech-progression")
require("data.stack-sizes")
require("data.quality")